Repository maisans-maid/Mai, pull requests merged in 2020-12, with the labels that each got.

#38 (update): Add market entries
  assets/json/market.json
Labels: database

#41 (update): ISSUE TEMPLATE (#41)
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: enhancement

#43 (fix): Embed unused when message is null (#43)
  events/guildMemberAdd.js
  events/guildMemberRemove.js
Labels: bug

#45 Update of market accessibility
  commands/social/market.js
Labels: enhancement

#48 Update README for v4 release
  README.md
Labels: documentation

#49 This keyword returns an empty object
  commands/anime/alprofile.js
Labels: bug

#50 typo error
  commands/setup/welcometoggle.js
Labels: typo

#51 Calling string functions on undefined values
  commands/social/transfer.js
  commands/social/withdraw.js
Labels: bug

#52 Use null-propagation/optional-chaining
  commands/anime/seiyuu.js
  commands/setup/watch.js
  commands/utility/steam.js
  util/chatbot.js
  util/handle.js
  util/permissions.js
Labels: clean-code

#54 Add Market Enteries
  assets/json/market.json
Labels: database

#55 Add the ability to transfer and delete items
  commands/social/deleteitem.js
  commands/social/gift.js
Labels: enhancement, new command

#57 (update): command UI changes
  commands/anime/anime.js
  commands/anime/malprofile.js
  package-lock.json
  package.json
  util/constants.js
Labels: enhancement, semver: patch
