Repository maisans-maid/Mai, pull requests merged in 2021-01, with the labels that each got.

#62 (fix): call replace method on null value
  commands/anime/alprofile.js
Labels: bug

#65 (fix): tip shows incorrect cooldown
  commands/social/tip.js
Labels: bug

#69 Typo fix
  commands/setup/setmute.js
Labels: bug

#68 (fix): bulkDelete returns undefined on collection
  commands/moderation/clear.js
Labels: bug

#70 (update): Version 4.0.3 update
  .env_example
  assets/fonts/captcha.ttf
  assets/fonts/handwriting.ttf
  assets/images/30-sec-timer.gif
  assets/json/flags.json
  assets/json/logoquiz.json
  commands/social/bet.js
  commands/social/game.js
  commands/social/profile.js
  commands/social/tip.js
  commands/utility/userinfo.js
  index.js
  package-lock.json
  package.json
  util/games/captcha.js
  util/games/country-flags.js
  util/games/hangman.js
  util/games/logoquiz.js
  util/games/typingquiz.js
Labels: database, enhancement, new command, semver: patch

#72 Create Continuous Integration
  .github/workflows/node.js.yml
Labels: enhancement

#71 (update): Version 4.0.4 update
  .github/workflows/node.js.yml
  README.md
  package-lock.json
  package.json
  test.js
Labels: semver: patch

#79 Add actions/dance command
  assets/json/images.json
  commands/action/dance.js
  struct/Images.js
Labels: database, new command

#77 Updating env
  .env_example
  config.js
  struct/Mongoose.js
Labels: enhancement

#80 (update): Fixes and changes for next patch.
  .env_example
  assets/json/command-database.json
  assets/json/images.json
  build.js
  commands/action/dance.js
  commands/fun/dogfact.js
  commands/social/gift.js
  commands/social/transfer.js
  config.js
  package-lock.json
  package.json
  struct/Images.js
  struct/Mongoose.js
Labels: database, dependencies, enhancement, semver: patch

#85 (update): add new market items
  assets/json/market.json
Labels: database
